name: Java CI with Auto-Merge

on:
  push:
    branches-ignore: [main]  # Запуск для всех веток, КРОМЕ main
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Auto-PR: ' + context.ref.replace('refs/heads/', ''),
              head: context.ref.replace('refs/heads/', ''),
              base: 'main',
              body: 'Автоматически созданный PR'
            })

  build:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew build

  auto-merge:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.ref.replace('refs/heads/', ''),
              state: 'open'
            });
            if (prs.data.length > 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prs.data[0].number,
                merge_method: 'squash'
              });
            }