name: Java CI with Gradle

on: [push] # Запуск при каждом push'е в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Получение кода из репозитория
      - uses: actions/checkout@v4
      
      # 2. Настройка JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # Кэширование для ускорения сборок
      
      # 3. Даем права на выполнение gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      # 4. Основная сборка проекта
      - name: Build with Gradle
        run: ./gradlew build
